spring:
  application:
    name: ling-xi
  jackson:
    time-zone: GMT+8
    date-format: yyyy-MM-dd HH:mm:ss
  profiles:
    active: @profilesActive@
  # swagger2兼容
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
  # db
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    hikari:
      minimum-idle: 5
      maximum-pool-size: 20
      idle-timeout: 500000
      max-lifetime: 540000
      connection-timeout: 60000
      connection-test-query: SELECT 1

mybatis:
  type-aliases-package: me.happycao.lingxi.model
  config-location: classpath:mybatis/mybatis-config.xml
  mapper-locations: classpath:mybatis/mapper/*.xml

logging:
  level:
    root: info
  file:
    path: log
  config: classpath:logback-spring.xml

# 此地址由nginx代理，即前端访问http://localhost/rss/ 指向 rss-path
rss-path:
  windowsPath: D:/data/rss
  # /data/html/rss
  linuxPath: /usr/local/var/www/rss